### ISSUE TITLE
Unable to install libreddit: An error occurred inside the app installation script

### ISSUE THREAD

**Issue by ctarx** [YunoHost-Apps/libreddit_ynh#11]
### Describe the bug

Corupt source

### Context

- Hardware: Old computer
- YunoHost version: 4.3.6.3 (stable)

### Steps to reproduce
    ```sh
    sudo yunohost app install libreddit
    ```
### Logs

https://paste.yunohost.org/raw/deledidoki

**Comment by ericgaspar** [comment]
The shasum for this release keep changing. I suspect the binaries are beeing updated upstream without new tag/release version...
Should be ok now (utile it change again...)

**Comment by ctarx** [comment]
Unfortunately the problem still persists.
https://paste.yunohost.org/raw/hanukubiko

**Comment by ericgaspar** [comment]
It may not yet be updated in the catalog.

try

```
sudo yunohost app install https://github.com/YunoHost-Apps/libreddit_ynh
```
