### ISSUE TITLE
Libreddit service not working

### ISSUE THREAD

**Issue by mg-dev25** [YunoHost-Apps/libreddit_ynh#14]
Hello, I tried to install and run Libreddit but the service in the Yunohost web interface tell me that it's not working, so I removed the app multiples time and tried to test the test branch, but It's still not working. The log tell "Failed to parse system call....", I tried to search if other people got the same problems, but I have found nothing. 

Here are some logs if that can helps. Thanks. 

https://paste.yunohost.org/senoduteta
https://paste.yunohost.org/raw/dezacefuge

**Comment by ericgaspar** [comment]
should be fixed
