### ISSUE TITLE
503 error when accessing

### ISSUE THREAD

**Issue by rndmh3ro** [YunoHost-Apps/libreddit_ynh#2]
I installed libreddit (both master and testing) without errors.
When I try to access libreddit via the browser, I get a 503 error. Since there is no logging, I then ran libreddit like this:
```
root@debian-4gb-nbg1-1:~# export ADDRESS=127.0.0.1
root@debian-4gb-nbg1-1:~# export PORT=8095
root@debian-4gb-nbg1-1:~# /var/www/libreddit/libreddit -a ${ADDRESS} -p ${PORT}
```

Then I got an error output:
```
Starting Libreddit...
Running Libreddit v0.22.5 on 127.0.0.1:8095!
thread 'tokio-runtime-worker' panicked at 'could not load platform certs: Custom { kind: InvalidData, error: "Could not load PEM file \"/usr/lib/ssl/certs/ca-certificates.crt\"" }', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-rustls-0.23.0/src/config.rs:31:62
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

The same issue is described here (without a solution): https://github.com/spikecodes/libreddit/issues/385 

The file `/usr/lib/ssl/certs/ca-certificates.crt` of course exists:
```
root@debian-4gb-nbg1-1:~# md5sum /usr/lib/ssl/certs/ca-certificates.crt
47589ca6e36c7e9fa463c70ea2ec9e10  /usr/lib/ssl/certs/ca-certificates.crt
```
Any ideas? I guess its unrelated to yunohost...

```
root@debian-4gb-nbg1-1:~# cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

**Comment by ericgaspar** [comment]
Instead of running from the command line you should go to the webadmin and see what is going on with Libreddit service and restart it from there and eventually share the logs

I can't reproduce this issue and I have no issue installing Libreddit

**Comment by rndmh3ro** [comment]
Same error: https://paste.yunohost.org/ogebebivuj

**Comment by ghost** [comment]
I'm having a similar problem where the libreddit service will not start due to `libreddit.service: Main process exited, code=exited, status=203/EXEC`

- [Log from installing](https://paste.yunohost.org/raw/yalupefaca)
- [Service log](https://paste.yunohost.org/fogurehiso)

**Comment by rndmh3ro** [comment]
I don't know what changed but when I tried it again today, it worked.
