### ISSUE TITLE
 An error occurred inside the app upgrade script

### ISSUE THREAD

**Issue by ctarx** [YunoHost-Apps/libreddit_ynh#24]
### Describe the bug

Upgrade the 'libreddit' app failed

### Context

- Hardware: Old computer
- YunoHost version: 11.0.10.2 (stable)

- `Libreddit (libreddit) from 0.25.1~ynh1 to 0.26.0~ynh1`

### Steps to reproduce

Upgrade application in a webadmin

### Expected behavior

Upgrading

### Logs
[https://paste.yunohost.org/raw/oqewerewat](https://paste.yunohost.org/raw/oqewerewat)

**Comment by ericgaspar** [comment]
what about the last version `0.27.0~ynh1`, do you get the same error?

**Comment by ctarx** [comment]
the only available update I see is `0.26.0~ynh1`

**Comment by ericgaspar** [comment]
0.27.0~ynh1 as been pushed one hour ago. should be available soon. or you can upgrade from CLI: `sudo yunohost app upgrade libreddit -u https://github.com/YunoHost-Apps/libreddit_ynh`

**Comment by ctarx** [comment]
`Upgrade of libreddit completed`
`version: 0.27.0~ynh1`

Thank you.
