### ISSUE TITLE
Corrupt source

### ISSUE THREAD

**Issue by stemy2** [YunoHost-Apps/libreddit_ynh#7]
### Describe the bug
Can't upgrade because of a "corrupt source".

### Context

- Hardware: Desktop PC
- YunoHost version: 4.3.6.3
- I have access to my server: Full
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no 
- Using, or trying to install package version/branch: master
- If upgrading, current package version: *can be found in the admin, or with `yunohost app info $app_id`*

### Steps to reproduce

    ```sh
    sudo yunohost app install the_app
    ```
- *If you used the webadmin, please perform the equivalent command from the CLI first.*
### Expected behavior

Upgrading.

### Logs

https://paste.yunohost.org/raw/egefufidiz

**Comment by ericgaspar** [comment]
#8 should fix it
